/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>
/* Header for class com_example_opencvexample_OpenCvNativeClass */

using namespace cv;
using namespace std;
#ifndef _Included_com_example_opencvexample_OpenCvNativeClass
#define _Included_com_example_opencvexample_OpenCvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opencvexample_OpenCvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */

int toGray(Mat img, Mat& gray);


JNIEXPORT jint JNICALL Java_com_example_opencvexample_opencvnative_OpenCvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
